services:
  stats-server:
    build: statistics/statistics-service
    image: statistics-service
    container_name: statistics-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=adminStats
      - SPRING_DATASOURCE_PASSWORD=adminStats

  stats-db:
    image: postgres:16.1
    container_name: stats-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_PASSWORD=adminStats
      - POSTGRES_USER=adminStats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - CLIENT=http://statistics-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=adminStats
      - SPRING_DATASOURCE_PASSWORD=adminStats

  main-db:
    image: postgres:16.1
    container_name: main-database
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_PASSWORD=adminEwm
      - POSTGRES_USER=adminEwm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10