DROP TABLE IF EXISTS EndpointHit;

CREATE TABLE IF NOT EXISTS EndpointHit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(16)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);
ё